**A. IMPORT LIBRARY**

In [42]:
import numpy as np
from numpy.linalg import det,inv,eig
from numpy import diag


**B. PROBLEMS AND SOLUTION**

*Apakah [1 3] adalah eigenvector dari ([[1 -1] , [6 4]])? Jika Iya, berapakah eigenvalue-nya?*

In [43]:
'Membuat matriks dan disimpan kedalam variabel A'
A = np.array([[1,-1],[6,4]])

In [44]:
'Eigen decomposition'
eig_val,eig_vec = eig(A)

In [45]:
'Menampilkan eigenvalue'
eig_val

array([2.5+1.93649167j, 2.5-1.93649167j])

In [46]:
'Menampilkan eigenvector'
eig_vec

array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
       [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]])

In [47]:
'Pengecekan eign vector'
[1/np.sqrt(10), 3/np.sqrt(10)]

[0.31622776601683794, 0.9486832980505138]

In [48]:
'Recontruction Matrix'
M_reconst = eig_vec.dot(diag(eig_val)).dot(inv(eig_vec))
M_reconst

array([[ 1.+0.j, -1.+0.j],
       [ 6.+0.j,  4.+0.j]])