**A. IMPORT LIBRARY**

In [8]:
import numpy as np
from numpy.linalg import det    # Library determinan
from numpy.linalg import inv    # Library invers

**B. PROBLEMS AND SOLUTION**

*Membuat tensor sesuai arahan soal*

In [9]:
T = np.array([[[23,50],[7,12]],[[75,21],[57,12]],[[57,67],[99,43]],[[87,26],[18,84]]])
           
print(T.shape)
print(T)

(4, 2, 2)
[[[23 50]
  [ 7 12]]

 [[75 21]
  [57 12]]

 [[57 67]
  [99 43]]

 [[87 26]
  [18 84]]]


*Melakukan perkalian dua buah matriks sesuai arahan soal*

In [10]:
A = np.array([[23,50,19],[7,12,109],[57,67,98]])
B = np.array([17,22,19])
print(A@B)

[1852 2454 4305]


*Melakukan Transpose, menghitung determinan, dan invers terhadap matrix yang telah diberikan*

In [11]:
C = np.array([[23,50,19],[7,12,109],[57,67,98]])
C

array([[ 23,  50,  19],
       [  7,  12, 109],
       [ 57,  67,  98]])

In [12]:
'Melakukan Transpose'
Transpose = C.T
print(Transpose)

[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


In [13]:
'Menghitung Determinan'
Determinan = det(C)
print(Determinan)

131344.0000000002


In [14]:
'Melakuakn Invers'
Invers = inv(C)
print(Invers)

[[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]]
